sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

install:
  - npm install

script:  
#  - npm run lint
#  - npm run lint:javascript
#  - npm run test
  - npm run bower_install
  - npm run build
  
after_success:
  - ./deploy.sh
  - npm run lh --score=96 $GOOGIEHOST_HOST